#! /usr/bin/sudo /bin/bash
# ---
# RightScript Name: Install Rsyslog
# Description: Installs and configures rsyslog for CloudSlayers use
# Inputs: {}
# Attachments: []
# ...

/usr/bin/add-apt-repository ppa:adiscon/v8-stable
/usr/bin/apt-get update
/usr/bin/apt-get -y install rsyslog
/bin/mkdir -p /log
/bin/mkdir -p /log/16
/bin/mkdir -p /log/17
/bin/mkdir -p /log/18
/bin/mkdir -p /log/19
/bin/mkdir -p /log/20
/bin/mkdir -p /log/21
/bin/mkdir -p /log/22
/bin/ln -l /log/16 /log/neutron
/bin/ln -l /log/17 /log/nova
/bin/ln -l /log/18 /log/cinder
/bin/ln -l /log/19 /log/keystone
/bin/ln -l /log/20 /log/glance
/bin/ln -l /log/21 /log/cloudplatform
/bin/ln -l /log/22 /log/

cat <<EOF > /etc/rsyslog.conf
#  /etc/rsyslog.conf    Configuration file for rsyslog v3.
#
#                       For more information see
#                       /usr/share/doc/rsyslog-doc/html/rsyslog_conf.html

#  /etc/rsyslog.conf    Configuration file for rsyslog v3.
#
#                       For more information see
#                       /usr/share/doc/rsyslog-doc/html/rsyslog_conf.html
\$MaxMessageSize 2k

#
# Preserve FQDN
#
\$PreserveFQDN off

#################
#### MODULES ####
#################

\$ModLoad imuxsock
\$ModLoad imklog
\$ModLoad imtcp
\$InputTCPServerBindRuleset remote
\$InputTCPServerRun 3389

###########################
#### GLOBAL DIRECTIVES ####
###########################

#
# Use default timestamp format.
# To enable high precision timestamps, comment out the following line.
#
\$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# Filter duplicated messages
\$RepeatedMsgReduction on

#
# Set temporary directory to buffer syslog queue
#
\$WorkDirectory /var/spool/rsyslog

#
# Set the default permissions for all log files.
#
\$FileOwner root
\$FileGroup adm
\$FileCreateMode 0640
\$DirCreateMode 0755
\$Umask 0022

#
# Include all config files in /etc/rsyslog.d
#
\$IncludeConfig /etc/rsyslog.d/*.conf
EOF

cat <<EOF > /etc/rsyslog.d/50-default.conf
# Generated by BASE rsyslog RightScript
# For more information see rsyslog.conf(5) and /etc/rsyslog.conf

\$template RemoteHost,"/log/%syslogfacility%/%HOSTNAME%.log"

# Local Logging
\$RuleSet local
*.info;mail.none;authpriv.none;cron.none   /var/log/messages
mail.*   -/var/log/maillog
cron.*   /var/log/cron
authpriv.*   /var/log/secure
*.emerg   :omusrmsg:*
uucp,news.crit   /var/log/spooler
local7.*   /var/log/boot.log
# use the local RuleSet as default if not specified otherwise
\$DefaultRuleset local


# Remote Logging
\$RuleSet remote
*.* ?RemoteHost
EOF

/usr/sbin/service rsyslog restart
